/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})

public class FoodParingPics implements org.apache.thrift.TBase<FoodParingPics, FoodParingPics._Fields>, java.io.Serializable, Cloneable, Comparable<FoodParingPics> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FoodParingPics");

  private static final org.apache.thrift.protocol.TField PIC_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("picName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PIC_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("picUrl", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FoodParingPicsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FoodParingPicsTupleSchemeFactory());
  }

  public String picName; // required
  public String picUrl; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PIC_NAME((short)1, "picName"),
    PIC_URL((short)2, "picUrl");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PIC_NAME
          return PIC_NAME;
        case 2: // PIC_URL
          return PIC_URL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PIC_NAME, new org.apache.thrift.meta_data.FieldMetaData("picName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PIC_URL, new org.apache.thrift.meta_data.FieldMetaData("picUrl", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FoodParingPics.class, metaDataMap);
  }

  public FoodParingPics() {
  }

  public FoodParingPics(
    String picName,
    String picUrl)
  {
    this();
    this.picName = picName;
    this.picUrl = picUrl;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FoodParingPics(FoodParingPics other) {
    if (other.isSetPicName()) {
      this.picName = other.picName;
    }
    if (other.isSetPicUrl()) {
      this.picUrl = other.picUrl;
    }
  }

  public FoodParingPics deepCopy() {
    return new FoodParingPics(this);
  }

  @Override
  public void clear() {
    this.picName = null;
    this.picUrl = null;
  }

  public String getPicName() {
    return this.picName;
  }

  public FoodParingPics setPicName(String picName) {
    this.picName = picName;
    return this;
  }

  public void unsetPicName() {
    this.picName = null;
  }

  /** Returns true if field picName is set (has been assigned a value) and false otherwise */
  public boolean isSetPicName() {
    return this.picName != null;
  }

  public void setPicNameIsSet(boolean value) {
    if (!value) {
      this.picName = null;
    }
  }

  public String getPicUrl() {
    return this.picUrl;
  }

  public FoodParingPics setPicUrl(String picUrl) {
    this.picUrl = picUrl;
    return this;
  }

  public void unsetPicUrl() {
    this.picUrl = null;
  }

  /** Returns true if field picUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetPicUrl() {
    return this.picUrl != null;
  }

  public void setPicUrlIsSet(boolean value) {
    if (!value) {
      this.picUrl = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PIC_NAME:
      if (value == null) {
        unsetPicName();
      } else {
        setPicName((String)value);
      }
      break;

    case PIC_URL:
      if (value == null) {
        unsetPicUrl();
      } else {
        setPicUrl((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PIC_NAME:
      return getPicName();

    case PIC_URL:
      return getPicUrl();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PIC_NAME:
      return isSetPicName();
    case PIC_URL:
      return isSetPicUrl();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FoodParingPics)
      return this.equals((FoodParingPics)that);
    return false;
  }

  public boolean equals(FoodParingPics that) {
    if (that == null)
      return false;

    boolean this_present_picName = true && this.isSetPicName();
    boolean that_present_picName = true && that.isSetPicName();
    if (this_present_picName || that_present_picName) {
      if (!(this_present_picName && that_present_picName))
        return false;
      if (!this.picName.equals(that.picName))
        return false;
    }

    boolean this_present_picUrl = true && this.isSetPicUrl();
    boolean that_present_picUrl = true && that.isSetPicUrl();
    if (this_present_picUrl || that_present_picUrl) {
      if (!(this_present_picUrl && that_present_picUrl))
        return false;
      if (!this.picUrl.equals(that.picUrl))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_picName = true && (isSetPicName());
    list.add(present_picName);
    if (present_picName)
      list.add(picName);

    boolean present_picUrl = true && (isSetPicUrl());
    list.add(present_picUrl);
    if (present_picUrl)
      list.add(picUrl);

    return list.hashCode();
  }

  @Override
  public int compareTo(FoodParingPics other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPicName()).compareTo(other.isSetPicName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPicName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.picName, other.picName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPicUrl()).compareTo(other.isSetPicUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPicUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.picUrl, other.picUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FoodParingPics(");
    boolean first = true;

    sb.append("picName:");
    if (this.picName == null) {
      sb.append("null");
    } else {
      sb.append(this.picName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("picUrl:");
    if (this.picUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.picUrl);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FoodParingPicsStandardSchemeFactory implements SchemeFactory {
    public FoodParingPicsStandardScheme getScheme() {
      return new FoodParingPicsStandardScheme();
    }
  }

  private static class FoodParingPicsStandardScheme extends StandardScheme<FoodParingPics> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FoodParingPics struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PIC_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.picName = iprot.readString();
              struct.setPicNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PIC_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.picUrl = iprot.readString();
              struct.setPicUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FoodParingPics struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.picName != null) {
        oprot.writeFieldBegin(PIC_NAME_FIELD_DESC);
        oprot.writeString(struct.picName);
        oprot.writeFieldEnd();
      }
      if (struct.picUrl != null) {
        oprot.writeFieldBegin(PIC_URL_FIELD_DESC);
        oprot.writeString(struct.picUrl);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FoodParingPicsTupleSchemeFactory implements SchemeFactory {
    public FoodParingPicsTupleScheme getScheme() {
      return new FoodParingPicsTupleScheme();
    }
  }

  private static class FoodParingPicsTupleScheme extends TupleScheme<FoodParingPics> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FoodParingPics struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPicName()) {
        optionals.set(0);
      }
      if (struct.isSetPicUrl()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPicName()) {
        oprot.writeString(struct.picName);
      }
      if (struct.isSetPicUrl()) {
        oprot.writeString(struct.picUrl);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FoodParingPics struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.picName = iprot.readString();
        struct.setPicNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.picUrl = iprot.readString();
        struct.setPicUrlIsSet(true);
      }
    }
  }

}

