/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})

public class WineReviewAndRatingData implements org.apache.thrift.TBase<WineReviewAndRatingData, WineReviewAndRatingData._Fields>, java.io.Serializable, Cloneable, Comparable<WineReviewAndRatingData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("WineReviewAndRatingData");

  private static final org.apache.thrift.protocol.TField REVIEWER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("reviewerName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RATE_FIELD_DESC = new org.apache.thrift.protocol.TField("rate", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField TIME_ELAPSED_FIELD_DESC = new org.apache.thrift.protocol.TField("timeElapsed", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField REVIEW_CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("reviewContent", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new WineReviewAndRatingDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new WineReviewAndRatingDataTupleSchemeFactory());
  }

  public String reviewerName; // required
  public double rate; // required
  public String timeElapsed; // required
  public String reviewContent; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REVIEWER_NAME((short)1, "reviewerName"),
    RATE((short)2, "rate"),
    TIME_ELAPSED((short)3, "timeElapsed"),
    REVIEW_CONTENT((short)4, "reviewContent");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REVIEWER_NAME
          return REVIEWER_NAME;
        case 2: // RATE
          return RATE;
        case 3: // TIME_ELAPSED
          return TIME_ELAPSED;
        case 4: // REVIEW_CONTENT
          return REVIEW_CONTENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RATE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REVIEWER_NAME, new org.apache.thrift.meta_data.FieldMetaData("reviewerName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RATE, new org.apache.thrift.meta_data.FieldMetaData("rate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.TIME_ELAPSED, new org.apache.thrift.meta_data.FieldMetaData("timeElapsed", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REVIEW_CONTENT, new org.apache.thrift.meta_data.FieldMetaData("reviewContent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(WineReviewAndRatingData.class, metaDataMap);
  }

  public WineReviewAndRatingData() {
  }

  public WineReviewAndRatingData(
    String reviewerName,
    double rate,
    String timeElapsed,
    String reviewContent)
  {
    this();
    this.reviewerName = reviewerName;
    this.rate = rate;
    setRateIsSet(true);
    this.timeElapsed = timeElapsed;
    this.reviewContent = reviewContent;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public WineReviewAndRatingData(WineReviewAndRatingData other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetReviewerName()) {
      this.reviewerName = other.reviewerName;
    }
    this.rate = other.rate;
    if (other.isSetTimeElapsed()) {
      this.timeElapsed = other.timeElapsed;
    }
    if (other.isSetReviewContent()) {
      this.reviewContent = other.reviewContent;
    }
  }

  public WineReviewAndRatingData deepCopy() {
    return new WineReviewAndRatingData(this);
  }

  @Override
  public void clear() {
    this.reviewerName = null;
    setRateIsSet(false);
    this.rate = 0.0;
    this.timeElapsed = null;
    this.reviewContent = null;
  }

  public String getReviewerName() {
    return this.reviewerName;
  }

  public WineReviewAndRatingData setReviewerName(String reviewerName) {
    this.reviewerName = reviewerName;
    return this;
  }

  public void unsetReviewerName() {
    this.reviewerName = null;
  }

  /** Returns true if field reviewerName is set (has been assigned a value) and false otherwise */
  public boolean isSetReviewerName() {
    return this.reviewerName != null;
  }

  public void setReviewerNameIsSet(boolean value) {
    if (!value) {
      this.reviewerName = null;
    }
  }

  public double getRate() {
    return this.rate;
  }

  public WineReviewAndRatingData setRate(double rate) {
    this.rate = rate;
    setRateIsSet(true);
    return this;
  }

  public void unsetRate() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RATE_ISSET_ID);
  }

  /** Returns true if field rate is set (has been assigned a value) and false otherwise */
  public boolean isSetRate() {
    return EncodingUtils.testBit(__isset_bitfield, __RATE_ISSET_ID);
  }

  public void setRateIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RATE_ISSET_ID, value);
  }

  public String getTimeElapsed() {
    return this.timeElapsed;
  }

  public WineReviewAndRatingData setTimeElapsed(String timeElapsed) {
    this.timeElapsed = timeElapsed;
    return this;
  }

  public void unsetTimeElapsed() {
    this.timeElapsed = null;
  }

  /** Returns true if field timeElapsed is set (has been assigned a value) and false otherwise */
  public boolean isSetTimeElapsed() {
    return this.timeElapsed != null;
  }

  public void setTimeElapsedIsSet(boolean value) {
    if (!value) {
      this.timeElapsed = null;
    }
  }

  public String getReviewContent() {
    return this.reviewContent;
  }

  public WineReviewAndRatingData setReviewContent(String reviewContent) {
    this.reviewContent = reviewContent;
    return this;
  }

  public void unsetReviewContent() {
    this.reviewContent = null;
  }

  /** Returns true if field reviewContent is set (has been assigned a value) and false otherwise */
  public boolean isSetReviewContent() {
    return this.reviewContent != null;
  }

  public void setReviewContentIsSet(boolean value) {
    if (!value) {
      this.reviewContent = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REVIEWER_NAME:
      if (value == null) {
        unsetReviewerName();
      } else {
        setReviewerName((String)value);
      }
      break;

    case RATE:
      if (value == null) {
        unsetRate();
      } else {
        setRate((Double)value);
      }
      break;

    case TIME_ELAPSED:
      if (value == null) {
        unsetTimeElapsed();
      } else {
        setTimeElapsed((String)value);
      }
      break;

    case REVIEW_CONTENT:
      if (value == null) {
        unsetReviewContent();
      } else {
        setReviewContent((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REVIEWER_NAME:
      return getReviewerName();

    case RATE:
      return getRate();

    case TIME_ELAPSED:
      return getTimeElapsed();

    case REVIEW_CONTENT:
      return getReviewContent();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REVIEWER_NAME:
      return isSetReviewerName();
    case RATE:
      return isSetRate();
    case TIME_ELAPSED:
      return isSetTimeElapsed();
    case REVIEW_CONTENT:
      return isSetReviewContent();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof WineReviewAndRatingData)
      return this.equals((WineReviewAndRatingData)that);
    return false;
  }

  public boolean equals(WineReviewAndRatingData that) {
    if (that == null)
      return false;

    boolean this_present_reviewerName = true && this.isSetReviewerName();
    boolean that_present_reviewerName = true && that.isSetReviewerName();
    if (this_present_reviewerName || that_present_reviewerName) {
      if (!(this_present_reviewerName && that_present_reviewerName))
        return false;
      if (!this.reviewerName.equals(that.reviewerName))
        return false;
    }

    boolean this_present_rate = true;
    boolean that_present_rate = true;
    if (this_present_rate || that_present_rate) {
      if (!(this_present_rate && that_present_rate))
        return false;
      if (this.rate != that.rate)
        return false;
    }

    boolean this_present_timeElapsed = true && this.isSetTimeElapsed();
    boolean that_present_timeElapsed = true && that.isSetTimeElapsed();
    if (this_present_timeElapsed || that_present_timeElapsed) {
      if (!(this_present_timeElapsed && that_present_timeElapsed))
        return false;
      if (!this.timeElapsed.equals(that.timeElapsed))
        return false;
    }

    boolean this_present_reviewContent = true && this.isSetReviewContent();
    boolean that_present_reviewContent = true && that.isSetReviewContent();
    if (this_present_reviewContent || that_present_reviewContent) {
      if (!(this_present_reviewContent && that_present_reviewContent))
        return false;
      if (!this.reviewContent.equals(that.reviewContent))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_reviewerName = true && (isSetReviewerName());
    list.add(present_reviewerName);
    if (present_reviewerName)
      list.add(reviewerName);

    boolean present_rate = true;
    list.add(present_rate);
    if (present_rate)
      list.add(rate);

    boolean present_timeElapsed = true && (isSetTimeElapsed());
    list.add(present_timeElapsed);
    if (present_timeElapsed)
      list.add(timeElapsed);

    boolean present_reviewContent = true && (isSetReviewContent());
    list.add(present_reviewContent);
    if (present_reviewContent)
      list.add(reviewContent);

    return list.hashCode();
  }

  @Override
  public int compareTo(WineReviewAndRatingData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetReviewerName()).compareTo(other.isSetReviewerName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReviewerName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reviewerName, other.reviewerName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRate()).compareTo(other.isSetRate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rate, other.rate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTimeElapsed()).compareTo(other.isSetTimeElapsed());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimeElapsed()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timeElapsed, other.timeElapsed);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReviewContent()).compareTo(other.isSetReviewContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReviewContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reviewContent, other.reviewContent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("WineReviewAndRatingData(");
    boolean first = true;

    sb.append("reviewerName:");
    if (this.reviewerName == null) {
      sb.append("null");
    } else {
      sb.append(this.reviewerName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rate:");
    sb.append(this.rate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("timeElapsed:");
    if (this.timeElapsed == null) {
      sb.append("null");
    } else {
      sb.append(this.timeElapsed);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("reviewContent:");
    if (this.reviewContent == null) {
      sb.append("null");
    } else {
      sb.append(this.reviewContent);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class WineReviewAndRatingDataStandardSchemeFactory implements SchemeFactory {
    public WineReviewAndRatingDataStandardScheme getScheme() {
      return new WineReviewAndRatingDataStandardScheme();
    }
  }

  private static class WineReviewAndRatingDataStandardScheme extends StandardScheme<WineReviewAndRatingData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, WineReviewAndRatingData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REVIEWER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.reviewerName = iprot.readString();
              struct.setReviewerNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RATE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.rate = iprot.readDouble();
              struct.setRateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TIME_ELAPSED
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.timeElapsed = iprot.readString();
              struct.setTimeElapsedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REVIEW_CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.reviewContent = iprot.readString();
              struct.setReviewContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, WineReviewAndRatingData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.reviewerName != null) {
        oprot.writeFieldBegin(REVIEWER_NAME_FIELD_DESC);
        oprot.writeString(struct.reviewerName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(RATE_FIELD_DESC);
      oprot.writeDouble(struct.rate);
      oprot.writeFieldEnd();
      if (struct.timeElapsed != null) {
        oprot.writeFieldBegin(TIME_ELAPSED_FIELD_DESC);
        oprot.writeString(struct.timeElapsed);
        oprot.writeFieldEnd();
      }
      if (struct.reviewContent != null) {
        oprot.writeFieldBegin(REVIEW_CONTENT_FIELD_DESC);
        oprot.writeString(struct.reviewContent);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class WineReviewAndRatingDataTupleSchemeFactory implements SchemeFactory {
    public WineReviewAndRatingDataTupleScheme getScheme() {
      return new WineReviewAndRatingDataTupleScheme();
    }
  }

  private static class WineReviewAndRatingDataTupleScheme extends TupleScheme<WineReviewAndRatingData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, WineReviewAndRatingData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetReviewerName()) {
        optionals.set(0);
      }
      if (struct.isSetRate()) {
        optionals.set(1);
      }
      if (struct.isSetTimeElapsed()) {
        optionals.set(2);
      }
      if (struct.isSetReviewContent()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetReviewerName()) {
        oprot.writeString(struct.reviewerName);
      }
      if (struct.isSetRate()) {
        oprot.writeDouble(struct.rate);
      }
      if (struct.isSetTimeElapsed()) {
        oprot.writeString(struct.timeElapsed);
      }
      if (struct.isSetReviewContent()) {
        oprot.writeString(struct.reviewContent);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, WineReviewAndRatingData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.reviewerName = iprot.readString();
        struct.setReviewerNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.rate = iprot.readDouble();
        struct.setRateIsSet(true);
      }
      if (incoming.get(2)) {
        struct.timeElapsed = iprot.readString();
        struct.setTimeElapsedIsSet(true);
      }
      if (incoming.get(3)) {
        struct.reviewContent = iprot.readString();
        struct.setReviewContentIsSet(true);
      }
    }
  }

}

